version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Rejected
    required: 2
    reset_on_push:
      enabled: false
    users:
    - atneik
    - battletoilet
    - dzearing
    - Jahnp
    - micahgodbolt
    - mikewheaton
    - philworthington
    - wdo3650
